name: sample-ruby
services:
  - name: api-ruby
    environment_slug: ruby
    github:
      repo: crossid/sample-ruby
      branch: main
      deploy_on_push: true
    envs:
      - key: ISSUER_BASE_URL
        value: "https://<tenant>.crossid.io/oauth2/"
      - key: CLIENT_ID
        value: "<client_id>"
      - key: CLIENT_SECRET
        value: "<client_secret>"
        type: SECRET
      - key: REDIRECT_URI
        value: "${_self.PUBLIC_URL}callback"